   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-deployment
  labels:
    app: minikube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minikube-deployment
  template:
    metadata:
      labels:
        app: minikube-deployment
    spec:
      containers:
      - name: minikube-deployment
        image: swethamba859/minikube-deployment:1.0
        ports:
        - containerPort: 8084
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: minikube-deployment
spec:
  selector:
    app: minikube-deployment
  type: NodePort
  ports:
    - protocol : TCP
      port: 8084
      targetPort: 8084
